### ISSUE TITLE
Needed Informations

### ISSUE THREAD

**Issue by lhumke** [Smart-City-SoSe-2022/Portal#1]
Hi, I need some Informations to create a docker template for your microservice.
I need following Informations:

- What programming languages are you going to use?
- What frameworks or libraries are you going to use to create your webserver, api, frontend?
- What DBMS do you want to use? MySQL, NoSQL, ...
- What IDE or text editor are you using during your development?
- Do you need to use any external APIs

**Comment by mrdanf** [comment]
- Language: JavaScript & Java or Python
- Frontend: Vue.js
- Backend: Java: SpringBoot or Python: Flask or Django
- DBMS: MySQL
- IDE: IntelliJ
- External APIs: Maybe OAuth?
