### ISSUE TITLE
Frontend Update Feature implementieren

### ISSUE THREAD

**Issue by mrdanf** [Smart-City-SoSe-2022/Portal#25]

**Comment by lhumke** [comment]
Dieses Issue hast du glaube ich in #30 abgearbeitet.

**Comment by lhumke** [comment]
Es wäre noch cool, wenn der Button zum Informationen ändern nicht angezeigt wird, solange der jwt cookie noch nicht gesetzt ist, bzw man nicht angemeldet ist

**Comment by lhumke** [comment]
Aber ansonsten würde ich sagen kann das Issue geschlossen werden

**Comment by mrdanf** [comment]
Ich habe mir das Issue #28 erstellt, bei dem es darum geht, dass die Buttons dem Login Status entsprechend angezeigt werden sollen. Also wie du sagtest, dass der Button zum Informationen ändern nicht angezeigt wird, solange der JWT Cookie nicht gesetzt wurde, also man nicht eingeloggt ist. Da setze ich mich noch dran.
